config/routes.rb
PocketSpritz::Application.routes.draw do
  resources :pocket_users

  root 'welcome#index'
  get 'queue' => 'pocket_users#queue'
  get 'queue/:id' => 'pocket_users#read'

  get 'test' => 'welcome#test_spritz'
  get 'spritz_login_success' => 'welcome#spritz_login_success'

end

app/models/pocket_user.rb
class PocketUser < ActiveRecord::Base
  attr_accessor :access_token
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pocket_users_controller.rb
require 'open-uri'

class PocketUsersController < ApplicationController
  before_action :set_pocket_user, only: [:show, :edit, :update, :destroy]

  # GET /pocket_users
  # GET /pocket_users.json
  def index
    @pocket_users = PocketUser.all
  end

  # GET /pocket_users/1
  # GET /pocket_users/1.json
  def show
  end

  # GET /pocket_users/new
  def new
    @pocket_user = PocketUser.new
  end

  # GET /pocket_users/1/edit
  def edit
  end

  # POST /pocket_users
  # POST /pocket_users.json
  def create
    @pocket_user = PocketUser.new(pocket_user_params)

    respond_to do |format|
      if @pocket_user.save
        format.html { redirect_to @pocket_user, notice: 'Pocket user was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pocket_user }
      else
        format.html { render action: 'new' }
        format.json { render json: @pocket_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pocket_users/1
  # PATCH/PUT /pocket_users/1.json
  def update
    respond_to do |format|
      if @pocket_user.update(pocket_user_params)
        format.html { redirect_to @pocket_user, notice: 'Pocket user was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pocket_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pocket_users/1
  # DELETE /pocket_users/1.json
  def destroy
    @pocket_user.destroy
    respond_to do |format|
      format.html { redirect_to pocket_users_url }
      format.json { head :no_content }
    end
  end

  def queue
    if session[:user_id]
      @user = PocketUser.find(session[:user_id])

      url = 'https://getpocket.com/v3/oauth/authorize'
      request = HTTPI::Request.new(url)
      request.body = '{"consumer_key":"26064-2500754fd1a2ea5a05e2f6a0", "code":"CODE"}'
      request.body = request.body.gsub 'CODE', @user.code
      request.headers = {"Content-Type" => "application/json"}

      returned_vars = CGI.parse(HTTPI.post(request).body)
      @user.access_token = returned_vars['access_token'].first
      @user.username     = returned_vars['username'].first

      url = 'https://getpocket.com/v3/get'
      request = HTTPI::Request.new(url)
      request.body = {
        :consumer_key => PocketSpritz::Application.config.pocket_web_api,
        :access_token => @user.access_token,
      }.to_json
      request.body = '{"consumer_key":"26064-2500754fd1a2ea5a05e2f6a0", "access_token":"TOKEN", "count":"10"}'
      request.body = request.body.gsub 'TOKEN', @user.access_token
      request.headers = {"Content-Type" => "application/json"}

      @user.current_queue = HTTPI.post(request).body
      @user.save!

      @username = @user.username
      @articles = JSON.parse(@user.current_queue)
      @articles = @articles['list'].first 5
    else
      @username = "Could not find |#{session[:user_id]}|"
    end
  end

  def read
    if session[:user_id]
      @user = PocketUser.find(session[:user_id])
      @articles = JSON.parse(@user.current_queue)
      @articles = @articles['list']

      @articles.each do |article_id,article|
        if article_id.to_i == params[:id].to_i
=begin
          doc = Nokogiri::HTML(open(article['resolved_url'])) 
          all_p = doc.css('p')
          @article_body = all_p
          @article = article
=end
          @article_url = article['resolved_url']
          break
        else
          @article_body = "I did not find it...#{article_id}|#{params[:id].to_i}|#{article}"
          @article = @articles.size
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pocket_user
      @pocket_user = PocketUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pocket_user_params
      params[:pocket_user]
    end
end

app/controllers/welcome_controller.rb
require 'net/http'
require 'net/https'
require 'pp'

class WelcomeController < ApplicationController

  def index
    @auth_params = {
      :consumer_key => PocketSpritz::Application.config.pocket_web_api,
      :redirect_uri => 'http://localhost:3000/queue',
    }.to_json

    @headers = { 
      'Content-Type' => 'application/json; charset=UTF-8',
      'X-Accept'     => 'application/json', 
    }

    url = 'https://getpocket.com/v3/oauth/request'

    request = HTTPI::Request.new(url)
    request.headers = @headers
    request.body = @auth_params

    @code = JSON.parse(HTTPI.put(request).body)['code']
    @user = PocketUser.new
    @user.code = @code
    @user.save!

    session[:user_id] = @user.id
    url = "https://getpocket.com/auth/authorize?request_token=#{@code}&redirect_uri=http://localhost:3000/queue"
    redirect_to url
  end

  def test_spritz
  end

  def spritz_login_success
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pocket_users_helper.rb
module PocketUsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PocketSpritz</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pocket_users/_form.html.erb
<%= form_for(@pocket_user) do |f| %>
  <% if @pocket_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pocket_user.errors.count, "error") %> prohibited this pocket_user from being saved:</h2>

      <ul>
      <% @pocket_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pocket_users/edit.html.erb
<h1>Editing pocket_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @pocket_user %> |
<%= link_to 'Back', pocket_users_path %>

app/views/pocket_users/index.html.erb
<h1>Listing pocket_users</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pocket_users.each do |pocket_user| %>
      <tr>
        <td><%= link_to 'Show', pocket_user %></td>
        <td><%= link_to 'Edit', edit_pocket_user_path(pocket_user) %></td>
        <td><%= link_to 'Destroy', pocket_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pocket user', new_pocket_user_path %>

app/views/pocket_users/new.html.erb
<h1>New pocket_user</h1>

<%= render 'form' %>

<%= link_to 'Back', pocket_users_path %>

app/views/pocket_users/queue.erb
Hello <%= @username %>!
<br />
<hr />
<br />
<table>
  <tr>
    <td>ID</td>
    <td>Title</td>
    <td>Excerpt</td>
  <tr>
  <% @articles.each do |article| %>
    <tr>
      <td><a href='<%= "queue/" + article[0].to_s %>'><%= article[0].to_s %></a></td>
      <td><%= article[1]['resolved_title'] %></td>
      <td><%= article[1]['excerpt'] %></td>
    <tr>
  <% end %>
</table>
<br />
<hr />
<br />
<%= 
@articles.pretty_inspect
%>

app/views/pocket_users/read.erb
<!-- jQuery dependency -->
<script type="text/javascript" src="//sdk.spritzinc.com/jQuery/jquery-2.1.0.min.js"></script>
<script type="text/javascript" src="//sdk.spritzinc.com/js/1.0/js/spritz.min.js"></script>

<!-- Global settings for the examples -->
<script type="text/javascript">
  var SpritzSettings = {
    clientId: "77cf1453ef585ab23",
    redirectUri: "http://localhost:3000/spritz_login_success",
    
  };
</script>


<div style='width: 100%;'><div style='margin: 0 auto; text-align: center;' data-role="spritzer" data-url="<%= @article_url %>"></div></div>

<iframe src='<%= @article_url %>' name='raw_article' style='width: 100%; height: 500px;'></iframe>

app/views/pocket_users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_pocket_user_path(@pocket_user) %> |
<%= link_to 'Back', pocket_users_path %>

app/views/welcome/index.erb
<%= @auth_params %>
<br />
<hr />
<br />
<%= @response.raw_body %>

app/views/welcome/spritz_login_success.erb
<!doctype html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>Spritz Login Success</title>
	</head>
	<body>
		<script type="text/javascript">
			var hash = window.location.hash;
			var origin = window.location.protocol + "//" + window.location.host;
			
			// postMessage does not work reliably in IE, pass the value through localStorage

            if (typeof(localStorage) !== 'undefined') {
                try {
                	localStorage.setItem("spritz.authResponse", hash);
            	}
            	catch(e) {
            		if(console) {
            			console.log(e, 'Can\'t write to localStorage');
            		}
            	}
            }

            if (window.opener) {
               window.opener.postMessage(hash, origin);
            }
		</script>
	</body>
</html>

app/views/welcome/test_spritz.erb
<!-- jQuery dependency -->
<script type="text/javascript" src="//sdk.spritzinc.com/jQuery/jquery-2.1.0.min.js"></script>
<script type="text/javascript" src="//sdk.spritzinc.com/js/1.0/js/spritz.min.js"></script>

<!-- Global settings for the examples -->
<script type="text/javascript">
  var SpritzSettings = {
    clientId: "77cf1453ef585ab23",
    redirectUri: "http://localhost:3000/spritz_login_success",
    
  };
</script>


<p><div data-role="spritzer" data-url="http://espn.go.com/nba/story/_/id/10949807/kevin-love-tells-minnesota-timberwolves-sign-extension-likes-chicago-bulls-golden-state-warriors"></div></p>